@testitem "ECC detector error model export" tags=[:ecc, :ecc_base] begin
    using Test
    using QuantumClifford
    using QuantumClifford.ECC
    using QuantumClifford.ECC: DetectorError, CodeCapacityDetectorErrorModel

    function target_rows(bits)
        collect(findall(!iszero, vec(bits)))
    end

    function expected_targets(code, q, pauli)
        H = parity_checks(code)
        n = code_n(code)
        O = faults_matrix(code)

        x_error = single_x(n, q)
        z_error = single_z(n, q)

        if pauli == :X
            detectors = target_rows(comm(H, x_error))
            observables = target_rows(@view O[:, q])
        elseif pauli == :Z
            detectors = target_rows(comm(H, z_error))
            observables = target_rows(@view O[:, n + q])
        elseif pauli == :Y
            detectors = target_rows((comm(H, x_error) .!= 0) .⊻ (comm(H, z_error) .!= 0))
            observables = target_rows((@view O[:, q]) .⊻ (@view O[:, n + q]))
        else
            error("unsupported test Pauli")
        end

        detectors, observables
    end

    function find_error(dem, q, pauli)
        only(filter(e -> e.qubit == q && e.pauli == pauli, dem.errors))
    end

    code = Steane7()
    dem = detector_error_model(code; px=0.01, py=0.02, pz=0.03)

    @test dem isa CodeCapacityDetectorErrorModel
    @test dem.num_detectors == code_s(code)
    @test dem.num_observables == 2 * code_k(code)
    @test length(dem.errors) == 3 * code_n(code)

    @test [(e.qubit, e.pauli) for e in dem.errors[1:6]] ==
          [(1, :X), (1, :Y), (1, :Z), (2, :X), (2, :Y), (2, :Z)]
    @test [e.probability for e in dem.errors[1:3]] == [0.01, 0.02, 0.03]

    for (q, pauli) in ((1, :X), (1, :Y), (1, :Z), (7, :Y))
        err = find_error(dem, q, pauli)
        detectors, observables = expected_targets(code, q, pauli)
        @test err.detectors == detectors
        @test err.observables == observables
    end

    z_only = detector_error_model(code; pz=0.125)
    @test length(z_only.errors) == code_n(code)
    @test all(e.pauli == :Z && e.probability == 0.125 for e in z_only.errors)

    @test_throws DomainError detector_error_model(code; px=-0.1)
    @test_throws DomainError detector_error_model(code; py=1.1)
    @test_throws DomainError detector_error_model(code; pz=Inf)

    io = IOBuffer()
    write_detector_error_model(io, z_only)
    text = String(take!(io))
    @test occursin("# Code-capacity detector error model generated by QuantumClifford.ECC", text)
    @test occursin("detector D0", text)
    @test occursin("logical_observable L0", text)
    @test occursin("error(0.125)", text)
    @test !occursin("error(0.0)", text)

    path = tempname() * ".dem"
    try
        write_detector_error_model(path, z_only)
        @test read(path, String) == text
    finally
        isfile(path) && rm(path)
    end
end
