env:
  JULIA_NUM_THREADS: auto

secrets:
  - CODECOV_TOKEN

steps:
  - label: "QuantumClifford - all non-hardware tests (local QECCore)"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          compiled_size_limit: 10737418240 # 10GiB
    commands:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --startup-file=no --color=yes -e 'import Pkg; Pkg.Apps.add("TestItemApp")'
      - >
        "$$(julia --startup-file=no -e
        'print(joinpath(first(DEPOT_PATH), "bin", "juliati")))" .
        --progress log
        --no-fail-on-detection-error
        --timeout none
        --check-bounds auto
        --threads 1
        --filter
        'startswith(package_name, "QuantumClifford") &&
        !(:cuda in tags) && !(:rocm in tags) && !(:opencl in tags)'
    agents:
      queue: "default-queue"

  - label: "QuantumClifford - GPU {{matrix.LABEL}} (local QECCore)"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          compiled_size_limit: 10737418240 # 10GiB
    commands:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --startup-file=no --color=yes -e 'import Pkg; Pkg.Apps.add("TestItemApp")'
      - >
        "$$(julia --startup-file=no -e
        'print(joinpath(first(DEPOT_PATH), "bin", "juliati")))" .
        --progress log
        --no-fail-on-detection-error
        --timeout none
        --check-bounds auto
        --max-workers 1
        --filter
        'startswith(package_name, "QuantumClifford") && :{{matrix.TAG}} in tags'
    agents:
      queue: "{{matrix.QUEUE}}"
    matrix:
      setup:
        LABEL: ["CUDA"]
        TAG: ["cuda"]
        QUEUE: ["cuda"]
      adjustments:
        - with:
            LABEL: "ROCm"
            TAG: "rocm"
            QUEUE: "rocm"
        - with:
            LABEL: "OpenCL"
            TAG: "opencl"
            QUEUE: "default-queue"

  - label: "QECCore - {{matrix.LABEL}} (local QuantumClifford)"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          compiled_size_limit: 10737418240 # 10GiB
      - JuliaCI/julia-test#v1:
          package: "QECCore"
          test_args: "{{matrix.TEST_ARGS}}"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - ./src
            - ./ext
            - ./lib/QECCore/src
            - ./lib/QECCore/ext
    commands:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
    agents:
      queue: "{{matrix.QUEUE}}"
    matrix:
      setup:
        LABEL: ["General"]
        QUEUE: ["default-queue"]
        TEST_ARGS: ["general"]
      adjustments:
        - with:
            LABEL: "JET"
            QUEUE: "default-queue"
            TEST_ARGS: "jet"

  - label: "Downstream {{matrix.PACKAGE}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          compiled_size_limit: 10737418240 # 10GiB
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";
        Pkg.add("{{matrix.PACKAGE}}");
        Pkg.build("{{matrix.PACKAGE}}");
        Pkg.test("{{matrix.PACKAGE}}");'
    matrix:
      setup:
        PACKAGE: ["QuantumSavory", "BPGates", "QuantumSymbolics"]

  - label: "Downstream (dev) {{matrix.PACKAGE}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
          compiled_size_limit: 10737418240 # 10GiB
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";
        Pkg.develop("{{matrix.PACKAGE}}");
        Pkg.build("{{matrix.PACKAGE}}");
        Pkg.test("{{matrix.PACKAGE}}");'
    matrix:
      setup:
        PACKAGE: ["QuantumSavory", "BPGates", "QuantumSymbolics"]
