env:
  CODECOV_TOKEN: adb3f22a-231a-4f7b-8ed4-7c6c56453cbe
  JULIA_NUM_THREADS: auto
  PYTHON: ""
  PYCALL_DEBUG_BUILD: yes
  
steps:
  - label: "Package Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "Downstream Breakage"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";'
        Pkg.add("QuantumSymbolics");
        Pkg.build("QuantumSymbolics");
        Pkg.test("QuantumSymbolics");
        Pkg.add("QuantumSavory");
        Pkg.build("QuantumSavory");
        Pkg.test("QuantumSavory");
        Pkg.add("BPGates");
        Pkg.build("BPGates");
        Pkg.test("BPGates");'
