env:
  CODECOV_TOKEN: adb3f22a-231a-4f7b-8ed4-7c6c56453cbe
  JULIA_NUM_THREADS: auto
  PYTHON: ""
  PYCALL_DEBUG_BUILD: yes

steps:
  - label: "Package Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "JET Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      JET_TEST: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ECC Code Properties"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_CODE_PROPERTIES: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ECC Encoding"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_ENCODING: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ECC Decoding"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_DECODING: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ECC Syndrome Measurement Correctness"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_SYNDROME_MEASUREMENT_CORRECTNESS: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
        pkg"dev .";'
  - label: "ECC Syndrome Circuit Equivalence"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_SYNDROME_CIRCUIT_EQUIVALENCE: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ECC Throws"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_THROWS: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ECC Bespoke Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ECC_BESPOKE_TESTS: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "CUDA Tests"
    agents:
      queue: cuda
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      #- QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      CUDA_TEST: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "ROCm Tests"
    agents:
      queue: rocm
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      #- QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      ROCm_TEST: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "OpenCL Tests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    env:
      OpenCL_TEST: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project='~' -e '
        using Pkg;
        pkg"dev .";'
  - label: "Downstream QuantumSavory"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";
        Pkg.add("QuantumSavory");
        Pkg.build("QuantumSavory");
        Pkg.test("QuantumSavory");'
  - label: "Downstream BPGates"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";
        Pkg.add("BPGates");
        Pkg.build("BPGates");
        Pkg.test("BPGates");'
  - label: "Downstream QuantumSymbolics"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - julia --project=$(mktemp -d) -e '
        using Pkg;
        pkg"dev .";
        Pkg.add("QuantumSymbolics");
        Pkg.build("QuantumSymbolics");
        Pkg.test("QuantumSymbolics");'
