env:
  CODECOV_TOKEN: adb3f22a-231a-4f7b-8ed4-7c6c56453cbe
  JULIA_NUM_THREADS: auto
  PYTHON: ""
  PYCALL_DEBUG_BUILD: yes
  
steps:
  - label: "CI Buildkite"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command:
      - echo "Julia depot path $${JULIA_DEPOT_PATH}"
      - mkdir -p "$${JULIA_DEPOT_PATH}/conda/3/x86_64"
      - julia --project='~' -e '
        using Pkg;
        ENV["PYTHON"] = "";
        Pkg.add("Conda");
        Pkg.add("PyCall");
        Pkg.build("PyCall");
        println("and now we dev the current package");
        pkg"dev .";'
      - julia --project='~' -e '
        using Pkg;
        ENV["PYTHON"] = "";
        Pkg.add("QuantumSavory");
        Pkg.build("QuantumSavory");
        Pkg.test("QuantumSavory");
        Pkg.add("BPGates");
        Pkg.build("BPGates");
        Pkg.test("BPGates");'