"""
    $TYPEDEF

The generalized toric code is specified by two Laurent polynomials `f(x,y)` and `g(x,y) over
``\\mathbb{F}_2``. These polynomials encode the local stabilizers of the `X` and `Z`-type operators.
The parameters `(α, β, γ)` define the geometry of the underlying twisted torus:

- ``\\alpha``: vertical period from lattice vector ``a_1 = (0, \\alpha)``
- ``\\beta``: horizontal extent from lattice vector ``a_2 = (\\beta, \\gamma)``
- ``\\gamma``: vertical shift applied when wrapping horizontally

The total number of physical qubits is ``n = 2*\\alpha\\beta``, corresponding to horizontal and
vertical edges in each unit cell. The parity-check matrices ``H_X`` and ``H_Z`` are constructed
following approach in Appendix B of [liang2025generalizedtoriccodestwisted](@cite). Qubits are
indexed row-by-row: for each `y`-coordinate, horizontal edges are listed first,then vertical edges.
Stabilizers are generated by translating the *origin* stabilizer, defined by the monomial supports of
`f` and `g`, across all ``(l_x, l_y)`` in ``0 ≤ l_x < \\beta``, ``0 ≤ l_y < \\alpha``. Translations
obey twisted boundary conditions determined by ``(\\alpha, \\beta, \\gamma)``, ensuring the matrices
retain a generalized cyclic structure.

The notable cases of Generalized toric codes include:

### Kitaev Toric Code

The Kitaev Toric code is defined by the Laurent polynomials ``f(x, y) = 1 + x`` and ``g(x, y) = 1 + y``. The
only independent monomial is 1, as all other monomials ``x^a y^b`` can be expressed as:  

```math
\\begin{aligned}
    x^a y^b = a_1 + p(x, y)f(x, y) + q(x, y)g(x, y)
\\end{aligned}
```

where ``a_1 \\in \\mathbb{Z}_2`` and ``p(x, y), q(x, y) \\in R``. For instance: ``x^2 = 1 + (1 + x)(1 + x)``. 

### Color Code

The Color code is defined by the Laurent polynomials ``f(x, y) = 1 + x + xy`` and ``g(x, y) = 1 + y + xy``. The
independent monomials are 1 and x. Other monomials follow:

```math
\\begin{aligned}
    x^a y^b = a_1 + a_x x + p(x, y)f(x, y) + q(x, y)g(x, y)
\\end{aligned}
```
 
The code has ``k_{\\text{max}} = 4``, reflecting its structure as a direct sum of two Kitaev codes.  

!!! note
    For simple polynomials, independent monomials can be identified manually. However, a systematic
    approach using **Gröbner basis** is necessary for general cases.  

### ``(-1, 3, 3, -1)``-Generalized Toric Code

The ``(-1, 3, 3, -1)``-Generalized Toric code corresponds to stabilizers in the Gross code
and ``(3,3)``-BB code. The Laurent polynomials are:

```math
\\begin{aligned}
    f(x, y) = 1 + x + x^{-1}y^3, \\quad g(x, y) = 1 + y + x^3 y^{-1},  
\\end{aligned}
```

### ``(-1, -3, 3, -1)``-Generalized Toric Code

The ``(-1, -3, 3, -1)``-Generalized Toric code corresponds to the (3, -3)-BB code. The
Laurent polynomials are:

```math
\\begin{aligned} 
    f(x, y) = 1 + x + x^{-1}y^{-3}, \\quad g(x, y) = 1 + y + x^3 y^{-1}.  
\\end{aligned}
```

# Examples

Here is an example of `[[[396, 8, ≤ 26]]` Generalized Toric Code from Table IV of [liang2025generalizedtoriccodestwisted](@cite).

```jldoctest
julia> using Oscar; using QuantumClifford; using QuantumClifford.ECC;

julia> R, (x,y) = laurent_polynomial_ring(GF(2), [:x, :y]);

julia> f = 1 + x + x^-1*y^-3;

julia> g = 1 + y + x^3*y^-1;

julia> α1 = (0, 66);

julia> α2 = (3, 18);

julia> c = GeneralizedToricCode(f, g, α1, α2);

julia> code_n(c), code_k(c)
(396, 8)
```

Here is an example of `[[[36, 2, d]]` Generalized Toric Code from Appendix B of [liang2025generalizedtoriccodestwisted](@cite).

```jldoctest
julia> using Oscar; using QuantumClifford; using QuantumClifford.ECC;

julia> R, (x,y) = laurent_polynomial_ring(GF(2), [:x, :y]);

julia> f = 1 + x;

julia> g = 1 + y;

julia> α1 = (0, 6);

julia> α2 = (3, 3);

julia> c = GeneralizedToricCode(f, g, α1, α2);

julia> code_n(c), code_k(c)
(36, 2)
```

### Fields
    $TYPEDFIELDS
"""    
struct GeneralizedToricCode <: AbstractCSSCode
    """Laurent polynomial over ``\\mathbb{F}_2`` defining horizontal–edge action of the X-type stabilizer"""
    f::LaurentMPolyWrap
    """Laurent polynomial over ``\\mathbb{F}_2`` defining vertical–edge action of the X-type stabilizer"""
    g::LaurentMPolyWrap
    """First lattice vector ``\\mathbf{a}_1 = (p_1, q_1)``, from which ``(\\alpha, \\beta, \\gamma)`` can
    be computed so that ``a_1 = (0, \\alpha)`` represents the same *generic* twisted torus under a unimodular transformation."""
    a1::Tuple{Int,Int}
    """Second lattice vector ``\\mathbf{a}_2 = (p_2, q_2)``, from which ``(\\alpha, \\beta, \\gamma)`` can
    be computed so that ``a_2 = (\\beta, \\gamma)`` represents the same *generic* twisted torus under a unimodular transformation."""
    a2::Tuple{Int,Int}

    function GeneralizedToricCode(f::LaurentMPolyWrap, g::LaurentMPolyWrap, a1::Tuple{Int,Int}, a2::Tuple{Int,Int})
        if a1[1] != 0
            α, β, γ, _, _ = _twisted_params(a1, a2)
            a1 = (0, α)
            a2 = (β, γ)
            return new(f, g, a1, a2)
        else
            return new(f, g, a1, a2)
        end
    end
end

function _twisted_params(a1::Tuple{Int,Int}, a2::Tuple{Int,Int})
    M = matrix(ZZ, 2, 2, [a1[1], a1[2], a2[1], a2[2]])
    H, U = hnf_with_transform(M)
    @assert(H == U*M)
    α = H[2,2]
    β = H[1,1]
    γ = H[1,2]
    return α, β, γ, H, U
end

function _monomial_terms(poly)
    coeffs = coefficients(poly)
    exps   = exponent_vectors(poly)
    terms = Tuple{Int,Int}[]
    for (c,e) in zip(coeffs, exps)
        if c != 0
            push!(terms, (Int(e[1]), Int(e[2])))
        end
    end
    return terms
end

function _move_index(i::Int, dx::Int, dy::Int, β::Int, γ::Int, n::Int, α::Int)
    dy_mod = mod(dy, α)
    i = mod(i + 2*β*dy_mod, n)
    if dx > 0
        for _ = 1:dx
            if mod(i,β) == (β-1)
                i = mod(i+1-(2*γ+1)*β, n)
            else
                i = mod(i+1,n)
            end
        end
    elseif dx < 0
        for _ = 1:(-dx)
            if mod(i,β) == 0
                i = mod(i-1+(2*γ+1)*β, n)
            else
                i = mod(i-1, n)
            end
        end
    end
    return i
end

function parity_matrix_xz(c::GeneralizedToricCode)
    α = c.a1[2]
    β = c.a2[1]
    γ = c.a2[2]
    f_terms = _monomial_terms(c.f)
    g_terms = _monomial_terms(c.g)
    n = 2*α*β
    cols = α*β
    base_horiz = 0
    base_vert  = β
    origin_av = Int[]
    for (ex,ey) in f_terms
        idx = _move_index(base_horiz, ex, ey, β, γ, n, α)
        push!(origin_av, idx)
    end
    for (ex,ey) in g_terms
        idx = _move_index(base_vert, ex, ey, β, γ, n, α)
        push!(origin_av, idx)
    end
    origin_av = unique(origin_av)
    origin_bp = Int[]
    for (ex,ey) in g_terms
        idx = _move_index(base_horiz, -ex, -ey, β, γ, n, α)
        push!(origin_bp, idx)
    end
    for (ex,ey) in f_terms
        idx = _move_index(base_vert, -ex, -ey, β, γ, n, α)
        push!(origin_bp, idx)
    end
    origin_bp = unique(origin_bp)
    HX = zeros(Int, n, cols)
    HZ = zeros(Int, n, cols)
    col = 1
    for lᵧ in 0:(α-1)
        for lₓ in 0:(β-1)
            for q in origin_av
                newq = _move_index(q, lₓ, lᵧ, β, γ, n, α)
                @assert 0 <= newq < n
                HX[newq+1, col] = 1
            end
            for q in origin_bp
                newq = _move_index(q, lₓ, lᵧ, β, γ, n, α)
                @assert 0 <= newq < n
                HZ[newq+1, col] = 1
            end
            col += 1
        end
    end
    return HX', HZ'
end

parity_matrix_x(c::GeneralizedToricCode) = parity_matrix_xz(c)[1]

parity_matrix_z(c::GeneralizedToricCode) = parity_matrix_xz(c)[2]
