"""
    DetectorError

One independent code-capacity error mechanism in a Stim detector error model.

The `detectors` and `observables` fields use Julia's 1-based indexing. They are
converted to Stim's 0-based `D#` and `L#` targets when written with
[`write_detector_error_model`](@ref).
"""
struct DetectorError
    probability::Float64
    qubit::Int
    pauli::Symbol
    detectors::Vector{Int}
    observables::Vector{Int}
end

"""
    CodeCapacityDetectorErrorModel

A detector error model generated directly from an error-correction code's parity
checks and logical fault matrix.
"""
struct CodeCapacityDetectorErrorModel
    num_detectors::Int
    num_observables::Int
    errors::Vector{DetectorError}
end

function _validate_dem_probability(p, name::Symbol)
    p isa Real || throw(DomainError(p, lazy"`$name` must be a real probability."))
    fp = Float64(p)
    isfinite(fp) || throw(DomainError(p, lazy"`$name` must be finite."))
    0 <= fp <= 1 || throw(DomainError(p, lazy"`$name` must be between 0 and 1."))
    return fp
end

_target_indices(bits) = collect(findall(!iszero, vec(bits)))

"""
    detector_error_model(code; px=0, py=0, pz=0)

Build a code-capacity Stim detector error model for `code`.

The detector order follows `parity_checks(code)` row order. Logical observable
targets follow the row order of [`faults_matrix`](@ref): logical-X observables
first, then logical-Z observables. The returned model stores Julia 1-based
indices internally; [`write_detector_error_model`](@ref) writes Stim's 0-based
`D#` and `L#` targets.
"""
function detector_error_model(code; px=0, py=0, pz=0)
    px = _validate_dem_probability(px, :px)
    py = _validate_dem_probability(py, :py)
    pz = _validate_dem_probability(pz, :pz)

    H = parity_checks(code)
    O = faults_matrix(code)
    n = code_n(code)
    k = code_k(code)
    errors = DetectorError[]

    for q in 1:n
        x_detectors = comm(H, single_x(n, q))
        z_detectors = comm(H, single_z(n, q))
        x_observables = @view O[:, q]
        z_observables = @view O[:, n + q]

        if px != 0
            push!(errors, DetectorError(
                px,
                q,
                :X,
                _target_indices(x_detectors),
                _target_indices(x_observables),
            ))
        end
        if py != 0
            push!(errors, DetectorError(
                py,
                q,
                :Y,
                _target_indices((x_detectors .!= 0) .⊻ (z_detectors .!= 0)),
                _target_indices(x_observables .⊻ z_observables),
            ))
        end
        if pz != 0
            push!(errors, DetectorError(
                pz,
                q,
                :Z,
                _target_indices(z_detectors),
                _target_indices(z_observables),
            ))
        end
    end

    return CodeCapacityDetectorErrorModel(code_s(code), 2k, errors)
end

function _print_dem_targets(io::IO, prefix::Char, targets)
    for target in targets
        print(io, ' ', prefix, target - 1)
    end
end

"""
    write_detector_error_model(io, dem)
    write_detector_error_model(path::AbstractString, dem)

Write a [`CodeCapacityDetectorErrorModel`](@ref) using Stim's `.dem` text syntax.
"""
function write_detector_error_model(io::IO, dem::CodeCapacityDetectorErrorModel)
    println(io, "# Code-capacity detector error model generated by QuantumClifford.ECC")
    println(io, "# Detector targets D0, D1, ... follow parity_checks(code) row order.")
    println(io, "# Logical targets L0, L1, ... follow faults_matrix(code) row order.")

    for detector in 0:(dem.num_detectors - 1)
        println(io, "detector D", detector)
    end
    for observable in 0:(dem.num_observables - 1)
        println(io, "logical_observable L", observable)
    end

    for err in dem.errors
        print(io, "error(", err.probability, ")")
        _print_dem_targets(io, 'D', err.detectors)
        _print_dem_targets(io, 'L', err.observables)
        print(io, " # ", err.pauli, err.qubit)
        println(io)
    end
end

function write_detector_error_model(path::AbstractString, dem::CodeCapacityDetectorErrorModel)
    open(path, "w") do io
        write_detector_error_model(io, dem)
    end
    return path
end
