"""
$(TYPEDEF)

A circuit operation representing an independent Stim detector error model mechanism.
With probability `probability`, this operation XORs all `detector_bits` and `logical_bits`
in a [`PauliFrame`](@ref).
"""
struct DetectorError{T<:Real,D,L} <: AbstractOperation
    probability::T
    detector_bits::NTuple{D,Int}
    logical_bits::NTuple{L,Int}

    function DetectorError{T,D,L}(
        probability::Real,
        detector_bits::NTuple{D,Int},
        logical_bits::NTuple{L,Int},
    ) where {T<:Real,D,L}
        0 <= probability <= 1 || throw(ArgumentError("Detector error probability must be in [0, 1]."))
        detectors = tuple(sort!(collect(detector_bits))...)
        logicals = tuple(sort!(collect(logical_bits))...)
        return new{T,D,L}(T(probability), detectors, logicals)
    end
end

function DetectorError(probability::Real, detector_bits, logical_bits)
    detectors = _canonical_detector_error_bits(detector_bits)
    logicals = _canonical_detector_error_bits(logical_bits)
    typed_probability = float(probability)
    return DetectorError{typeof(typed_probability),length(detectors),length(logicals)}(
        typed_probability, detectors, logicals
    )
end

_canonical_detector_error_bits(bits) = tuple(sort!(collect(Int, bits))...)

function concrete_typeparams(::Type{DetectorError})
    return [(Float64, detector_count, logical_count)
            for detector_count in 0:8
            for logical_count in 0:8]
end

"""
$(TYPEDEF)

Vector-like circuit returned by [`read_detector_error_model`](@ref).

The measurement columns produced by `pftrajectories(circuit)` are ordered as all detector
bits first, followed by all logical observable bits.
"""
struct DetectorErrorModelCircuit{T,O<:AbstractVector{T}} <: AbstractVector{T}
    operations::O
    detector_count::Int
    logical_count::Int

    function DetectorErrorModelCircuit(
        operations::O,
        detector_count::Integer,
        logical_count::Integer,
    ) where {T,O<:AbstractVector{T}}
        detector_count >= 0 || throw(ArgumentError("detector_count must be non-negative."))
        logical_count >= 0 || throw(ArgumentError("logical_count must be non-negative."))
        return new{T,O}(operations, Int(detector_count), Int(logical_count))
    end
end

Base.IndexStyle(::Type{<:DetectorErrorModelCircuit}) = IndexLinear()
Base.size(circuit::DetectorErrorModelCircuit) = size(circuit.operations)
Base.length(circuit::DetectorErrorModelCircuit) = length(circuit.operations)
Base.getindex(circuit::DetectorErrorModelCircuit, i::Int) = circuit.operations[i]
Base.iterate(circuit::DetectorErrorModelCircuit) = iterate(circuit.operations)
Base.iterate(circuit::DetectorErrorModelCircuit, state) = iterate(circuit.operations, state)

"""Return the number of detector bits in an imported detector error model circuit."""
detector_count(circuit::DetectorErrorModelCircuit) = circuit.detector_count

"""Return the number of logical observable bits in an imported detector error model circuit."""
logical_observable_count(circuit::DetectorErrorModelCircuit) = circuit.logical_count

affectedqubits(::DetectorError) = ()
affectedbits(op::DetectorError) = (op.detector_bits..., op.logical_bits...)

function apply!(frame::PauliFrame, op::DetectorError)
    bits = affectedbits(op)
    isempty(bits) && return frame
    @inbounds for f in eachindex(frame)
        if rand() < op.probability
            for bit in bits
                frame.measurements[f, bit] ⊻= true
            end
        end
    end
    return frame
end

function _create_pauliframe(circuit::DetectorErrorModelCircuit; trajectories=5000)
    return PauliFrame(trajectories, 1, circuit.detector_count + circuit.logical_count)
end

function compactify_circuit(circuit::DetectorErrorModelCircuit)
    return DetectorErrorModelCircuit(
        compactify_circuit(circuit.operations),
        circuit.detector_count,
        circuit.logical_count,
    )
end

"""
$(TYPEDSIGNATURES)

Return the detector measurement columns from a [`PauliFrame`](@ref) generated by an imported
detector error model circuit.
"""
function detector_measurements(frame::PauliFrame, circuit::DetectorErrorModelCircuit)
    return measurements(frame)[:, 1:circuit.detector_count]
end

"""
$(TYPEDSIGNATURES)

Return the logical observable measurement columns from a [`PauliFrame`](@ref) generated by an
imported detector error model circuit.
"""
function logical_observable_measurements(frame::PauliFrame, circuit::DetectorErrorModelCircuit)
    first_logical = circuit.detector_count + 1
    last_logical = circuit.detector_count + circuit.logical_count
    return measurements(frame)[:, first_logical:last_logical]
end

struct _DetectorErrorSpec{T}
    probability::T
    detectors::Vector{Int}
    logicals::Vector{Int}
end

mutable struct _DetectorErrorModelParseState
    detector_offset::Int
    max_detector::Int
    max_logical::Int
    errors::Vector{_DetectorErrorSpec{Float64}}
end

_DetectorErrorModelParseState() = _DetectorErrorModelParseState(0, -1, -1, _DetectorErrorSpec{Float64}[])

struct _DetectorErrorModelInstruction
    name::String
    arguments::Vector{Float64}
    targets::Vector{String}
end

"""
$(TYPEDSIGNATURES)

Read a Stim detector error model (`.dem`) file and return a vector-like circuit accepted by
[`pftrajectories`](@ref).

The returned circuit stores detector outputs first and logical observable outputs after them.
Use [`detector_measurements`](@ref) and [`logical_observable_measurements`](@ref) to split
the columns after sampling.
"""
function read_detector_error_model(path::AbstractString)
    return open(path, "r") do io
        _detector_error_model_circuit_from_string(read(io, String); source=path)
    end
end

detector_error_model_circuit(path::AbstractString) = read_detector_error_model(path)

function detector_error_model_circuit(io::IO; source="<io>")
    return _detector_error_model_circuit_from_string(read(io, String); source)
end

function _detector_error_model_circuit_from_string(text::AbstractString; source="<string>")
    lines = split(text, '\n')
    state = _DetectorErrorModelParseState()
    _parse_detector_error_model_block!(state, lines, 1, length(lines), source)
    return _build_detector_error_model_circuit(state)
end

function _build_detector_error_model_circuit(state::_DetectorErrorModelParseState)
    detector_count = state.max_detector + 1
    logical_count = state.max_logical + 1
    operations = AbstractOperation[]
    for error in state.errors
        detector_bits = (detector + 1 for detector in error.detectors)
        logical_bits = (detector_count + logical + 1 for logical in error.logicals)
        push!(operations, DetectorError(error.probability, detector_bits, logical_bits))
    end
    return DetectorErrorModelCircuit(operations, detector_count, logical_count)
end

function _parse_detector_error_model_block!(
    state::_DetectorErrorModelParseState,
    lines::Vector{SubString{String}},
    first_line::Int,
    last_line::Int,
    source,
)
    line_number = first_line
    while line_number <= last_line
        line = _strip_detector_error_model_comment(lines[line_number])
        if isempty(line)
            line_number += 1
            continue
        end
        line == "}" && _dem_parse_error(source, line_number, "unexpected block terminator")
        if endswith(line, "{")
            instruction = _parse_detector_error_model_instruction(strip(chop(line)), source, line_number)
            instruction.name == "repeat" || _dem_parse_error(
                source, line_number, "only repeat blocks are supported"
            )
            repeat_count = _repeat_count(instruction, source, line_number)
            block_end = _find_detector_error_model_block_end(lines, line_number + 1, last_line, source)
            for _ in 1:repeat_count
                _parse_detector_error_model_block!(state, lines, line_number + 1, block_end - 1, source)
            end
            line_number = block_end + 1
        else
            instruction = _parse_detector_error_model_instruction(line, source, line_number)
            _apply_detector_error_model_instruction!(state, instruction, source, line_number)
            line_number += 1
        end
    end
    return state
end

function _find_detector_error_model_block_end(lines, first_line::Int, last_line::Int, source)
    depth = 0
    for line_number in first_line:last_line
        line = _strip_detector_error_model_comment(lines[line_number])
        isempty(line) && continue
        if endswith(line, "{")
            depth += 1
        elseif line == "}"
            if depth == 0
                return line_number
            end
            depth -= 1
        end
    end
    _dem_parse_error(source, first_line, "unterminated repeat block")
end

function _strip_detector_error_model_comment(line)
    return strip(first(split(String(line), '#'; limit=2)))
end

function _parse_detector_error_model_instruction(line::AbstractString, source, line_number::Int)
    parsed = match(
        r"^([A-Za-z][A-Za-z0-9_]*)(?:\[[^\]\r\n]*\])?(?:\(([^)]*)\))?(?:[ \t]+(.*))?$",
        line,
    )
    isnothing(parsed) && _dem_parse_error(source, line_number, "could not parse instruction")
    name_capture = something(parsed.captures[1], "")
    isempty(name_capture) && _dem_parse_error(source, line_number, "missing instruction name")
    target_capture = parsed.captures[3]

    name = lowercase(String(name_capture))
    arguments = _parse_detector_error_model_arguments(parsed.captures[2], source, line_number)
    targets = target_capture === nothing ? String[] : String.(split(String(target_capture)))
    return _DetectorErrorModelInstruction(name, arguments, targets)
end

function _parse_detector_error_model_arguments(arguments, source, line_number::Int)
    if isnothing(arguments) || isempty(strip(arguments))
        return Float64[]
    end
    parsed = Float64[]
    for argument in split(arguments, ',')
        value = tryparse(Float64, strip(argument))
        isnothing(value) && _dem_parse_error(source, line_number, "invalid numeric argument")
        push!(parsed, value)
    end
    return parsed
end

function _apply_detector_error_model_instruction!(
    state::_DetectorErrorModelParseState,
    instruction::_DetectorErrorModelInstruction,
    source,
    line_number::Int,
)
    if instruction.name == "error"
        _apply_detector_error_instruction!(state, instruction, source, line_number)
    elseif instruction.name == "detector"
        _apply_detector_declaration!(state, instruction, source, line_number)
    elseif instruction.name == "logical_observable"
        _apply_logical_observable_declaration!(state, instruction, source, line_number)
    elseif instruction.name == "shift_detectors"
        _apply_shift_detectors!(state, instruction, source, line_number)
    elseif instruction.name == "repeat"
        _dem_parse_error(source, line_number, "repeat must be followed by a block")
    else
        _dem_parse_error(source, line_number, "unsupported instruction `$(instruction.name)`")
    end
    return state
end

function _apply_detector_error_instruction!(
    state::_DetectorErrorModelParseState,
    instruction::_DetectorErrorModelInstruction,
    source,
    line_number::Int,
)
    length(instruction.arguments) == 1 || _dem_parse_error(
        source, line_number, "error instructions require exactly one probability argument"
    )
    probability = only(instruction.arguments)
    0 <= probability <= 1 || _dem_parse_error(source, line_number, "error probability must be in [0, 1]")
    detectors = Set{Int}()
    logicals = Set{Int}()
    for target in instruction.targets
        if target == "^"
            continue
        elseif startswith(target, "D")
            detector = state.detector_offset + _parse_nonnegative_int(target[2:end], source, line_number)
            state.max_detector = max(state.max_detector, detector)
            _toggle!(detectors, detector)
        elseif startswith(target, "L")
            logical = _parse_nonnegative_int(target[2:end], source, line_number)
            state.max_logical = max(state.max_logical, logical)
            _toggle!(logicals, logical)
        else
            _dem_parse_error(source, line_number, "error target `$target` is not supported")
        end
    end
    push!(
        state.errors,
        _DetectorErrorSpec(probability, sort!(collect(detectors)), sort!(collect(logicals))),
    )
    return state
end

function _apply_detector_declaration!(
    state::_DetectorErrorModelParseState,
    instruction::_DetectorErrorModelInstruction,
    source,
    line_number::Int,
)
    isempty(instruction.targets) && _dem_parse_error(
        source, line_number, "detector instructions require at least one detector target"
    )
    for target in instruction.targets
        startswith(target, "D") || _dem_parse_error(
            source, line_number, "detector target `$target` is not supported"
        )
        detector = state.detector_offset + _parse_nonnegative_int(target[2:end], source, line_number)
        state.max_detector = max(state.max_detector, detector)
    end
    return state
end

function _apply_logical_observable_declaration!(
    state::_DetectorErrorModelParseState,
    instruction::_DetectorErrorModelInstruction,
    source,
    line_number::Int,
)
    isempty(instruction.targets) && _dem_parse_error(
        source, line_number, "logical_observable instructions require at least one logical target"
    )
    for target in instruction.targets
        startswith(target, "L") || _dem_parse_error(
            source, line_number, "logical_observable target `$target` is not supported"
        )
        logical = _parse_nonnegative_int(target[2:end], source, line_number)
        state.max_logical = max(state.max_logical, logical)
    end
    return state
end

function _apply_shift_detectors!(
    state::_DetectorErrorModelParseState,
    instruction::_DetectorErrorModelInstruction,
    source,
    line_number::Int,
)
    length(instruction.targets) == 1 || _dem_parse_error(
        source, line_number, "shift_detectors requires exactly one numeric target"
    )
    shift = _parse_nonnegative_int(only(instruction.targets), source, line_number)
    state.detector_offset += shift
    return state
end

function _repeat_count(instruction::_DetectorErrorModelInstruction, source, line_number::Int)
    isempty(instruction.arguments) || _dem_parse_error(
        source, line_number, "repeat does not accept parenthesized arguments"
    )
    length(instruction.targets) == 1 || _dem_parse_error(
        source, line_number, "repeat requires exactly one numeric target"
    )
    return _parse_nonnegative_int(only(instruction.targets), source, line_number)
end

function _parse_nonnegative_int(text::AbstractString, source, line_number::Int)
    value = tryparse(Int, text)
    (isnothing(value) || value < 0) && _dem_parse_error(
        source, line_number, "`$text` is not a non-negative integer"
    )
    return value
end

function _toggle!(values::Set{Int}, value::Int)
    if value in values
        delete!(values, value)
    else
        push!(values, value)
    end
    return values
end

function _dem_parse_error(source, line_number::Int, message)
    throw(ArgumentError("Error parsing detector error model at $source:$line_number: $message."))
end
